export const INPUT_FIELD_SUCCESS = 'INPUT_FIELD_SUCCESS';
export const INPUT_FIELD_FAIL = 'INPUT_FIELD_FAIL';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_ADDRESS_DATA = 'SET_ADDRESS_DATA';
export const SET_DURATION_DATA = 'SET_DURATION_DATA';
