export const INPUT_FIELD_SUCCESS = 'INPUT_FIELD_SUCCESS';
export const INPUT_FIELD_FAIL = 'INPUT_FIELD_FAIL';
export const IP_FETCH_PENDING = 'IP_FETCH_PENDING';
export const IP_FETCH_SUCCESS = 'IP_FETCH_SUCCESS';
export const IP_FETCH_FAIL = 'IP_FETCH_FAIL';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
